Hw04 lru cache
KirillLavrentev/hw-otus pull request #4
Opened 2024-01-28 18:43 UTC by KirillLavrentev

2024-05-22 09:33 UTC, ityulkanov approved these changes

2024-05-22 09:34 UTC, ityulkanov commented on hw04_lru_cache/.gitignore
> +try*
кмк тут лишнее добавили)

2024-05-22 09:37 UTC, ityulkanov requested changes

2024-05-22 09:37 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		}
вот тут ошибка. Извиняюсь, рано принял) У вас тут не учтено условие в o(1), нужно все же поправить. Конкретно здесь - o(n)

2024-05-22 09:37 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		}
Чтобы внести правки дам подсказку - у вас в listItem.Value можно записывать interface{} т.е. любой элемент.

2024-05-22 19:35 UTC, KirillLavrentev commented on hw04_lru_cache/cache.go
> +		}
Поправил, теперь поиск осуществляется за O(1)

2024-05-23 14:38 UTC, ityulkanov approved these changes

2024-05-30 11:06 UTC, merged